name: CI/CD Pipeline for Cloud Run

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Authenticate to Google Cloud using Workload Identity Federation
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/${{ env.PROJECT_ID }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-deploy@${{ env.PROJECT_ID }}.iam.gserviceaccount.com'

      # Step 3: Set up Google Cloud SDK (gcloud CLI)
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      # Step 4: Configure Docker to authenticate with Google Artifact Registry
      - name: Authenticate Docker with Artifact Registry
        run: |
          gcloud auth configure-docker europe-central2-docker.pkg.dev

      # Step 5: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t europe-central2-docker.pkg.dev/${{ env.PROJECT_ID }}/homepage .

      # Step 6: Push the Docker image to Google Artifact Registry
      - name: Push Docker image to Artifact Registry
        run: |
          docker push europe-central2-docker.pkg.dev/${{ env.PROJECT_ID }}/homepage

      # Step 7: Deploy the image to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy homepage \
            --image europe-central2-docker.pkg.dev/${{ env.PROJECT_ID }}/homepage \
            --region europe-central2 \
            --platform managed \
            --allow-unauthenticated
